### ISSUE TITLE
What is a reach API?

### ISSUE THREAD

**Issue by smolinari** [xpepermint/contextablejs#5]
I've seen this term used in a [couple](https://github.com/xpepermint/contextablejs) of [places](https://xpepermint.gitbooks.io/vue-js-cheatsheet/content/application_context.html) (copy and paste?) and I can't find any kind of reference to such an API. Could it be "reach" should be "rich"? 😄 

Scott

**Comment by xpepermint** [comment]
Ehm... LOL ;). Fixed :).

**Comment by smolinari** [comment]
Glad you didn't take it the wrong way. :smile: :+1: 

Scott
