### ISSUE TITLE
Include type definitions in the npm package

### ISSUE THREAD

**Issue by BigForNothing** [xpepermint/contextablejs#9]
Can you please include the type definitions inside the type definition files? 

http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by xpepermint** [comment]
Types definition inside `package.json` should be enough. Make sure you are using the latest `typescript` version.
```
{
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  ...
}
```

**Comment by BigForNothing** [comment]
Sorry, you are correct. I was looking at the package as installed, which is still 3.1.0 (and doesn't include it). Looks like 3.2.0 will have it.

**Comment by xpepermint** [comment]
Good. I'll close the issue then.
